import './globals.css'
import { ClerkProvider } from '@clerk/nextjs'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Header from './components/Header'
import styles from './styles/styles.module.scss'
import { auth } from '@clerk/nextjs';
const inter = Inter({ subsets: ['latin'] })
export const metadata: Metadata = {
  title: 'Jvelin UI',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const { userId } = auth();
  return (
    <ClerkProvider appearance={{
      
    }} afterSignInUrl='/create-organization' afterSignUpUrl='/create-organization'>
      <html lang="en">
        <body className={inter.className}>
          <main className="flex min-h-screen flex-col"> 
            <Header />          
            {children}  
          </main>
        </body>
      </html>
    </ClerkProvider>
  )
}
