import './globals.css'
import { ClerkProvider } from '@clerk/nextjs'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import React, { useState } from 'react'
import Sidebar from './components/Sidebar'
import Header from './components/Header'
import DashboardLayout from './components/DashboardLayout'
import styles from './styles/styles.module.scss'
import { auth } from '@clerk/nextjs'
import { currentUser } from '@clerk/nextjs'
const inter = Inter({ subsets: ['latin'] })
export const metadata: Metadata = {
  title: 'Jvelin UI',
  description: 'Generated by create next app',
}
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const { userId } = auth();   
  const user = currentUser();  
  return (
    <ClerkProvider 
      appearance={{}} 
      afterSignInUrl='/create-organization' 
      afterSignUpUrl='/create-organization'
    >
      <html lang="en">
        <body className={inter.className}>
          {userId?<> 
            <div className="min-h-screen flex">          
              <DashboardLayout children ={children} userId={userId} />
            </div>
            {/* <div className="min-h-screen flex">
              <div className="w-217 flex-none ...">
                <Sidebar isExpanded={isExpanded} />
              </div>
              <main className="flex-1 min-w-0 overflow-auto ...">
                <Header isExpanded={isExpanded} setIsExpanded={setIsExpanded} />
                <div className='container mx-auto p-4'>     
                  {children}  
                </div>
              </main>
            </div> */}
          </>:<>
            <main className="flex min-h-screen flex-col">
              {children}  
            </main>
          </>}
        </body>
      </html>
    </ClerkProvider>
  )
}
